### ISSUE TITLE
Incomplete definition errors when making charm

### ISSUE THREAD

**Issue by bbuenz** [JHUISI/charm#135]
Hi I am trying to build charm on os.x 10.12 for python 2.7 but it's failing to compile the charm.core.math.integer module
The first error:

cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -DBENCHMARK_ENABLED=1 -Icharm/core/utilities/ -Icharm/core/benchmark/ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c charm/core/math/integer/integermodule.c -o build/temp.macosx-10.12-intel-2.7/charm/core/math/integer/integermodule.o
charm/core/math/integer/integermodule.c:75:21: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'int'
      [-Wshorten-64-to-32]
        int size, i, tmp = Py_SIZE(p);
                     ~~~   ^~~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/object.h:116:56: note: expanded from macro 'Py_SIZE'
#define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
charm/core/math/integer/integermodule.c:129:19: error: incomplete definition of type 'struct bignum_st'
                for(i = 0; i < m->dmax; i++) {
                               ~^

**Comment by jakinyele** [comment]
This likely means one of the dependencies wasn't installed or the headers are installed in a non-standard location. Can you confirm?

**Comment by bachp** [comment]
I ran into a similar issue while trying to compile against OpenSSL 1.1.0.

```
building 'charm.core.math.integer' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -DBENCHMARK_ENABLED=1 -Icharm/core/utilities/ -Icharm/core/benchmark/ -I/usr/include/python3.6m -c charm/core/math/integer/integermodule.c -o build/temp.linux-x86_64-3.6/charm/core/math/integer/integermodule.o
charm/core/math/integer/integermodule.c: In function ‘bnToLongObj’:
charm/core/math/integer/integermodule.c:129:19: error: dereferencing pointer to incomplete type ‘BIGNUM {aka struct bignum_st}’
   for(i = 0; i < m->dmax; i++) {
                   ^~
```

I think BIGNUM is an internal API of OpenSSL and maybe the API has changed.

**Comment by bachp** [comment]
I can confirm that it is working with OpenSSL 1.0.2.

I used the following patch to make it compile against my local OpenSSL 1.0 version.

```
From 253be9b108f4f07851db6885a9d94863fc5c3cf7 Mon Sep 17 00:00:00 2001
From: Pascal Bach <pascal.bach@nextrem.ch>
Date: Mon, 1 May 2017 23:29:30 +0200
Subject: [PATCH] Explicitly use openssl 1.0

---
 setup.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/setup.py b/setup.py
index 495c171a..21b7807f 100644
--- a/setup.py
+++ b/setup.py
@@ -198,11 +198,11 @@ if opt.get('PAIR_MOD') == 'yes':
 if opt.get('INT_MOD') == 'yes':
    replaceString(lib_config_file, "int_lib=libs ", "int_lib=libs.gmp")
    integer_module = Extension(math_prefix + '.integer', 
-                            include_dirs = [utils_path,
+                            include_dirs = ["/usr/include/openssl-1.0", utils_path,
                                             benchmark_path],
                             sources = [math_path + 'integer/integermodule.c', 
                                         utils_path + 'base64.c'], 
-                            libraries=['gmp', 'crypto'], define_macros=_macros, undef_macros=_undef_macro,
+                            libraries=['gmp', '/usr/lib/libcrypto.so.1.0.0'], define_macros=_macros, undef_macros=_undef_macro,
                             library_dirs=library_dirs, runtime_library_dirs=runtime_library_dirs)
    _ext_modules.append(integer_module)
    
-- 
2.12.2

```

**Comment by jakinyele** [comment]
Thanks for letting us know. We'll be adding support for OpenSSL 1.1+ very soon.

**Comment by ShangyanLi** [comment]
I am using python3.5 and have been receiving the `struct bignum_st` error, although using python2.7 works perfectly fine. Any idea why this might be?
Thanks in advance!

**Comment by jakinyele** [comment]
Closing as part of issue cleanup — this issue is very old and likely no longer relevant with the current codebase (v0.63). Feel free to reopen if still applicable.
