### ISSUE TITLE
charm-crypto compilation fails with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by purchawek** [JHUISI/charm#209]
During compilation with make (directly from sources here on master) i get the following compilation error:

```
charm/core/math/integer/integermodule.c:130:6: error: dereferencing pointer to incomplete type ‘BIGNUM’ {aka ‘struct bignum_st’}
  if(p->neg != 0) {
```

Changing it to use `BN_is_negative` fixes the error but I've seen that this approach was also erroneous as presented in #194 .

I believe that what should be done is conditional compilation based on the version of OpenSSL installed and supporting both APIs simultaneously but I may be wrong. If you agree, I may try to do this.

**Comment by jakinyele** [comment]
@purchawek Yeah, that is correct. And I was trying to figure out which versions of OpenSSL `BN_is_negative` is missing. Please go ahead. Thanks!

**Comment by VikasGowdaLV** [comment]
Hey guys, @purchawek @jakinyele 
Even I am facing the same issue, did we find the solution lately?
I was using openSSL 1.0.0 and even after upgrading to 1.1.1 there is no help
Thanks!

**Comment by Sumasrikanth** [comment]
@VikasGowdaLV :Did u find the solution. if yes help me out. for me this type error is shown

charm/core/math/integer/integermodule.c: In function ‘bnToLongObj’:
charm/core/math/integer/integermodule.c:130:19: error: dereferencing pointer to incomplete type ‘BIGNUM’ {aka ‘struct bignum_st’}
  130 |   for(i = 0; i < m->dmax; i++) {
      |                   ^~
charm/core/math/integer/integermodule.c: In function ‘mpzToBN’:
charm/core/math/integer/integermodule.c:167:6: warning: implicit declaration of function ‘bn_expand2’ [-Wimplicit-function-declaration]
  167 |   if(bn_expand2(b, size) == NULL)
      |      ^~~~~~~~~~
charm/core/math/integer/integermodule.c:167:26: warning: comparison between pointer and integer
  167 |   if(bn_expand2(b, size) == NULL)
      |                          ^~
charm/core/math/integer/integermodule.c:171:3: warning: implicit declaration of function ‘bn_correct_top’ [-Wimplicit-function-declaration]
  171 |   bn_correct_top(b);
      |   ^~~~~~~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [Makefile:29: all] Error 1
